### PR TITLE
Sad multiverse br

### PR DESCRIPTION
**Pull request by shamakh96**
Full change of can_write() function : 
direct access to the registers of  TM4C123

### CODE REVIEW

**Review by autosarzs — CHANGES_REQUESTED** [review]
Please don't merge on the main branch made the request again but to merge on the DevCan branch :) 

I gonna start the review after the request made for the DevCan

**Comment by autosarzs** [comment]
And please the branch name suppose to be related to the functionality not to the team :)

**Comment by shamakh96** [comment]
working on it  :+1:

**Comment by shamakh96** [comment]
i think i'll just wait to watch the recorded video session :'D, then work on it :+1:

**Comment by autosarzs** [comment]
I believe so :D :D

**Pull request closed without merging**
